{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurityStandard }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurityStandard }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurityStandard }}
{{- end }}
