{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orders-api.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orders-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "orders-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingressNamespaceSelector.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    # DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # HTTPS to Azure services (Key Vault, ACR, Storage)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.0.0/16
      ports:
        - protocol: TCP
          port: 443
{{- end }}
