{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "orders-api.fullname" . }}-kv
  namespace: {{ .Values.namespace.name }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ required "serviceAccount.azureWorkloadIdentityClientId is required (pass --set)" .Values.serviceAccount.azureWorkloadIdentityClientId | quote }}
    keyvaultName: {{ required "keyVault.name is required (pass --set)" .Values.keyVault.name | quote }}
    cloudName: {{ .Values.keyVault.cloudName | quote }}
    tenantId: {{ required "keyVault.tenantId is required (pass --set)" .Values.keyVault.tenantId | quote }}
    objects: |
      array:
{{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
{{- end }}
  secretObjects:
    - secretName: {{ include "orders-api.fullname" . }}-secrets
      type: Opaque
      data:
{{- range .Values.keyVault.secrets }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
{{- end }}
{{- end }}
