{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    azure.workload.identity/client-id: {{ required "serviceAccount.azureWorkloadIdentityClientId is required (pass --set)" .Values.serviceAccount.azureWorkloadIdentityClientId | quote }}
  labels:
    azure.workload.identity/use: "true"
    {{- include "orders-api.labels" . | nindent 4 }}
{{- end }}
