{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: disk.csi.azure.com
parameters:
  skuName: {{ .Values.storageClass.skuName }}
  cachingMode: {{ .Values.storageClass.cachingMode }}
  fsType: {{ .Values.storageClass.fsType }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
