apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-api-data
  namespace: orders
  labels:
    app.kubernetes.io/name: orders-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-zrs
  resources:
    requests:
      storage: 20Gi
