###############################################################################
# Workload Identity ServiceAccount.
# Annotate with the AAD client id of a User-Assigned Managed Identity that
# has been federated to this SA via "az identity federated-credential create".
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-api-sa
  namespace: orders
  annotations:
    azure.workload.identity/client-id: "REPLACE-WITH-UAMI-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
